In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from  sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [52]:
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

In [9]:
data=pd.read_csv('../data/raw/creditcard.csv')

In [10]:
data.size

8829017

In [11]:
data.shape

(284807, 31)

In [13]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [14]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [15]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [16]:
data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [17]:
#data is imbalanced so let's seperate it
legit=data[data.Class==0]
fraudulent=data[data.Class==1]

In [18]:
print(legit.shape)
print(fraudulent.shape)

(284315, 31)
(492, 31)

In [21]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [24]:
fraudulent.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [25]:
#compare values for both transactions
data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

##### Under Sampling
* building a sample dataset containing similar distribution of normal transactions and fraudulant transactions

* fraudulant transactions-492

In [26]:
legit_sample=legit.sample(n=492)

In [27]:
new_dataset= pd.concat([legit_sample,fraudulent],axis=0)

In [28]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
164526,116783.0,-0.513177,0.119525,-0.174453,-2.444747,0.002798,-0.635482,0.420882,-0.917540,-1.119860,...,1.286700,1.295894,-0.169774,-0.384203,-0.317197,-0.114468,0.501073,0.220695,87.75,0
259886,159316.0,-0.551576,0.092722,0.049345,-0.464676,-0.885291,2.503760,0.841588,0.118611,-0.453386,...,0.137812,1.417151,0.031929,-1.454002,-0.868796,-0.416171,-0.202788,-0.013577,272.00,0
90466,63033.0,0.917929,-1.888738,0.257366,-1.097736,-1.878739,-0.872499,-0.522360,-0.312182,-1.922289,...,-0.265099,-1.104574,-0.061492,0.349006,0.019061,-0.514073,-0.020133,0.082416,319.99,0
124836,77440.0,-1.287325,1.734479,0.340723,-0.099207,-0.399895,-0.591444,-0.106434,0.942888,-0.814317,...,-0.178952,-0.664187,0.035333,-0.050291,-0.041131,0.083744,0.109021,0.007561,8.99,0
190128,128696.0,-0.510079,1.057945,0.664574,1.113112,-1.121280,1.477075,-2.596879,-5.022185,-0.067349,...,-2.767065,0.021848,-0.039552,0.479012,0.872947,-0.301518,0.110619,0.231103,80.00,0

In [30]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [31]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93343.315041,-0.002642,0.076083,0.017246,0.067807,-0.026530,-0.076335,0.026870,-0.060079,0.069939,...,-0.001611,-0.014151,-0.019193,-0.016906,-0.019747,-0.002744,-0.004899,-0.019354,-0.000842,89.079492
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [34]:
#splitting the data into Features and Targets
X= new_dataset.drop(columns='Class')
y= new_dataset['Class']

In [35]:
print(X.shape)
print(X.columns)

(984, 30)
Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount'],
      dtype='str')

* Splitting the data into Training data and Testing data

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, stratify=y, random_state=2)

* Model Training

In [38]:
logreg=LogisticRegression()

In [39]:
logreg.fit(X_train, y_train)

d:\fraud-detection-system\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [44]:
y_train_pred=logreg.predict(X_train)
training_data_accuracy= accuracy_score(y_train, y_train_pred)

In [45]:
print(training_data_accuracy)

0.9466327827191868

* predictions

In [46]:
y_test_pred=logreg.predict(X_test)
test_data_accuracy=accuracy_score(y_test, y_test_pred)

In [47]:
print(test_data_accuracy)

0.9238578680203046

* probabilities (for ROC-AUC)

In [49]:
y_train_prob= logreg.predict_proba(X_train)[:, 1]
y_test_prob= logreg.predict_proba(X_test)[:, 1]

In [50]:
print(confusion_matrix(y_train, y_train_pred))
print(classification_report(y_train, y_train_pred))
print("ROC-AUC:", roc_auc_score(y_train, y_train_prob))

[[381  12]
 [ 30 364]]
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       393
           1       0.97      0.92      0.95       394

    accuracy                           0.95       787
   macro avg       0.95      0.95      0.95       787
weighted avg       0.95      0.95      0.95       787

ROC-AUC: 0.9783585848800713

* Testing

In [51]:
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))
print('ROC-AUC: ', roc_auc_score(y_test, y_test_prob))

[[94  5]
 [10 88]]
              precision    recall  f1-score   support

           0       0.90      0.95      0.93        99
           1       0.95      0.90      0.92        98

    accuracy                           0.92       197
   macro avg       0.93      0.92      0.92       197
weighted avg       0.92      0.92      0.92       197

ROC-AUC:  0.9674293960008246

In [53]:
rf=RandomForestClassifier(n_estimators=200, random_state=42, class_weight='balanced')
rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=200,
                       random_state=42)

In [54]:
y_rf_pred=rf.predict(X_test)
y_rf_prob= rf.predict_proba(X_test)[:, 1]

In [55]:
print(confusion_matrix(y_test, y_rf_pred))
print(classification_report(y_test, y_rf_pred))
print('ROC-AUC: ', roc_auc_score(y_test, y_rf_prob))

[[95  4]
 [12 86]]
              precision    recall  f1-score   support

           0       0.89      0.96      0.92        99
           1       0.96      0.88      0.91        98

    accuracy                           0.92       197
   macro avg       0.92      0.92      0.92       197
weighted avg       0.92      0.92      0.92       197

ROC-AUC:  0.972737579880437

In [60]:
# SAVE PROCESSED DATA
new_dataset.to_csv("../data/processed/processed_data.csv", index=False)

# SAVE MODEL
import pickle
with open("../models/model.pkl", "wb") as f:
    pickle.dump(logreg, f)

print("Saved successfully")

Saved successfully

In [61]:
print(X_test.iloc[0])

Time      41233.000000
V1          -10.645800
V2            5.918307
V3          -11.671043
V4            8.807369
V5           -7.975501
V6           -3.586806
V7          -13.616797
V8            6.428169
V9           -7.368451
V10         -12.888158
V11           6.854953
V12         -13.211695
V13           1.035612
V14         -13.778956
V15           1.040448
V16         -11.290328
V17         -20.578022
V18          -7.547824
V19           3.118480
V20          -0.046170
V21           2.571970
V22           0.206809
V23          -1.667801
V24           0.558419
V25          -0.027898
V26           0.354254
V27           0.273329
V28          -0.152908
Amount        0.000000
Name: 42756, dtype: float64